#!/bin/bash

OLDSUM=`cat /var/lib/cron.md5`
NEWSUM=`md5sum /etc/crontab`

if [ "$OLDSUM" != "$NEWSUM" ]
then
	md5sum /etc/crontab > /var/lib/cron.md5
	printf "$(date)\nWARNING - CRONTAB WAS MODIFIED\n" | mail -s "Crontab was modified" root@localhost
fi
